/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/local": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Local */
        post: operations["login_local_api_v1_auth_local_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Detail */
        get: operations["event_detail_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_v1_me_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Follows */
        put: operations["follows_api_v1_me_follows_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Preferences */
        patch: operations["preferences_api_v1_me_preferences_patch"];
        trace?: never;
    };
    "/api/v1/events/{event_id}/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Selection */
        put: operations["selection_api_v1_events__event_id__selection_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Link */
        post: operations["add_link_api_v1_events__event_id__links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/links/{link_id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block */
        post: operations["block_api_v1_me_links__link_id__block_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/creators/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creator Resolve */
        post: operations["creator_resolve_api_v1_me_creators_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creator Add */
        post: operations["creator_add_api_v1_me_creators_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/creators/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Creator Delete */
        delete: operations["creator_delete_api_v1_me_creators__channel_id__delete"];
        options?: never;
        head?: never;
        /** Creator Update */
        patch: operations["creator_update_api_v1_me_creators__channel_id__patch"];
        trace?: never;
    };
    "/api/v1/me/creators/{channel_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Creator Impact */
        get: operations["creator_impact_api_v1_me_creators__channel_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/creators/{channel_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creator Refresh */
        post: operations["creator_refresh_api_v1_me_creators__channel_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews */
        get: operations["reviews_api_v1_me_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/reviews/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Decide */
        post: operations["review_decide_api_v1_me_reviews__match_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/links/{link_id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Pin */
        post: operations["link_pin_api_v1_me_links__link_id__pin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/config/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Config */
        get: operations["export_config_api_v1_me_config_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/config/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Config */
        post: operations["import_config_api_v1_me_config_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/feed/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Address */
        get: operations["address_api_v1_me_feed_address_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/feed/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate */
        post: operations["rotate_api_v1_me_feed_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/feed/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_api_v1_me_feed_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/feed/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feed Preview */
        get: operations["feed_preview_api_v1_me_feed_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/local/providers/{provider}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sync */
        post: operations["trigger_sync_api_v1_local_providers__provider__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCreator */
        AddCreator: {
            /** Url */
            url: string;
            /** Scope Keys */
            scope_keys?: string[];
            /**
             * Preview
             * @default true
             */
            preview: boolean;
            /**
             * Recap
             * @default true
             */
            recap: boolean;
            /** Expected Revision */
            expected_revision: number;
        };
        /** AddLink */
        AddLink: {
            /** Url */
            url: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "live" | "preview" | "recap" | "watch_along";
        };
        /** CalendarUserView */
        CalendarUserView: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Revision */
            revision: number;
            config: components["schemas"]["Config-Output"];
            /** Creators */
            creators: components["schemas"]["CreatorView"][];
            feed: components["schemas"]["FeedView"];
        };
        /** Config */
        "Config-Input": {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Follows */
            follows?: components["schemas"]["Follow"][];
            /** Creators */
            creators?: components["schemas"]["CreatorFollow-Input"][];
            preferences?: components["schemas"]["Preferences-Input"];
            /** Event Overrides */
            event_overrides?: components["schemas"]["EventOverride"][];
            /** Link Overrides */
            link_overrides?: components["schemas"]["LinkOverride"][];
        };
        /** Config */
        "Config-Output": {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Follows */
            follows: components["schemas"]["Follow"][];
            /** Creators */
            creators: components["schemas"]["CreatorFollow-Output"][];
            preferences: components["schemas"]["Preferences-Output"];
            /** Event Overrides */
            event_overrides: components["schemas"]["EventOverride"][];
            /** Link Overrides */
            link_overrides: components["schemas"]["LinkOverride"][];
        };
        /** CoverageView */
        CoverageView: {
            /** Dataset */
            dataset: string;
            /** Complete */
            complete: boolean;
            /** Note */
            note: string;
        };
        /** CreatorFollow */
        "CreatorFollow-Input": {
            /** Channel Id */
            channel_id: string;
            /** Scope Keys */
            scope_keys?: string[];
            /**
             * Preview
             * @default true
             */
            preview: boolean;
            /**
             * Recap
             * @default true
             */
            recap: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** CreatorFollow */
        "CreatorFollow-Output": {
            /** Channel Id */
            channel_id: string;
            /** Scope Keys */
            scope_keys: string[];
            /**
             * Preview
             * @default true
             */
            preview: boolean;
            /**
             * Recap
             * @default true
             */
            recap: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** CreatorIdentity */
        CreatorIdentity: {
            /** Channel Id */
            channel_id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /** CreatorRemovalImpact */
        CreatorRemovalImpact: {
            /** Automatic Removed */
            automatic_removed: number;
            /** Manual Retained */
            manual_retained: number;
            /** Revision */
            revision: number;
        };
        /** CreatorView */
        CreatorView: {
            /** Channel Id */
            channel_id: string;
            /** Scope Keys */
            scope_keys: string[];
            /**
             * Preview
             * @default true
             */
            preview: boolean;
            /**
             * Recap
             * @default true
             */
            recap: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Name */
            name: string;
            /** Last Error */
            last_error: string;
            /** Sync Status */
            sync_status: string;
            /** Last Synced At */
            last_synced_at: string | null;
            /** Websub Status */
            websub_status: string;
        };
        /** EventList */
        EventList: {
            /** Items */
            items: components["schemas"]["EventView"][];
            coverage: components["schemas"]["CoverageView"];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** EventOverride */
        EventOverride: {
            /** Event Key */
            event_key: string;
            /**
             * State
             * @enum {string}
             */
            state: "include" | "exclude";
        };
        /** EventView */
        EventView: {
            /** Id */
            id: string;
            /** Source Key */
            source_key: string;
            /** Competition Id */
            competition_id: string;
            /** Sport */
            sport: string;
            /** Title */
            title: string;
            /** Starts At */
            starts_at: string | null;
            /** Local Date */
            local_date: string | null;
            /** Time Precision */
            time_precision: string;
            /** Timezone */
            timezone: string;
            /** Duration */
            duration: number;
            /** Venue */
            venue: string;
            /** Status */
            status: string;
            /** Participants */
            participants: components["schemas"]["ParticipantView"][];
            /** Provider */
            provider: string;
            /** Source Url */
            source_url: string;
            /** Updated At */
            updated_at: string;
            /** Demo */
            demo: boolean;
            /** Included */
            included: boolean;
            /** Links */
            links: components["schemas"]["LinkView"][];
            /** Description */
            description: string;
            /** Description In Feed */
            description_in_feed: boolean;
        };
        /** FeedAction */
        FeedAction: {
            /** Confirmed */
            confirmed: boolean;
        };
        /** FeedView */
        FeedView: {
            /** Revision */
            revision: number;
            /** Updated At */
            updated_at: string;
            /** Paused */
            paused: boolean;
            /** Status */
            status: string;
            /** Event Count */
            event_count: number;
        };
        /** Follow */
        Follow: {
            /**
             * Type
             * @enum {string}
             */
            type: "team" | "competition" | "event" | "series";
            /** Source Key */
            source_key: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportInput */
        ImportInput: {
            config: components["schemas"]["Config-Input"];
            /**
             * Mode
             * @default merge
             * @enum {string}
             */
            mode: "merge" | "replace";
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /** Expected Revision */
            expected_revision: number;
            /** Confirmation */
            confirmation?: string | null;
        };
        /** ImportPreviewView */
        ImportPreviewView: {
            /** Added */
            added: number;
            /** Removed */
            removed: number;
            /** Unresolved */
            unresolved: string[];
            /** Revision */
            revision: number;
            /** Confirmation */
            confirmation: string;
            /** Applied */
            applied: boolean;
        };
        /** LinkAddedView */
        LinkAddedView: {
            /** Id */
            id: string;
            event: components["schemas"]["EventView"];
        };
        /** LinkOverride */
        LinkOverride: {
            /** Event Key */
            event_key: string;
            /** Url */
            url: string;
            /**
             * State
             * @enum {string}
             */
            state: "block" | "pin";
        };
        /** LinkView */
        LinkView: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Kind */
            kind: string;
            /** Platform */
            platform: string;
            /** Creator */
            creator: string;
            /** Origin */
            origin: string;
            /** Access */
            access: string;
            /** Regions */
            regions: string[];
            /** Pinned */
            pinned: boolean;
            /** Created At */
            created_at: string;
        };
        /** OverrideInput */
        OverrideInput: {
            /** Expected Revision */
            expected_revision: number;
            /**
             * State
             * @enum {string}
             */
            state: "include" | "exclude" | "reset";
        };
        /** ParticipantView */
        ParticipantView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /** Color */
            color: string;
        };
        /** Preferences */
        "Preferences-Input": {
            /**
             * Timezone
             * @default Asia/Shanghai
             */
            timezone: string;
            /**
             * Locale
             * @default zh-CN
             * @enum {string}
             */
            locale: "zh-CN" | "en";
            /** Watch Region */
            watch_region?: string | null;
            /**
             * Spoiler Free
             * @default true
             */
            spoiler_free: boolean;
            /**
             * Transparent
             * @default true
             */
            transparent: boolean;
        };
        /** Preferences */
        "Preferences-Output": {
            /**
             * Timezone
             * @default Asia/Shanghai
             */
            timezone: string;
            /**
             * Locale
             * @default zh-CN
             * @enum {string}
             */
            locale: "zh-CN" | "en";
            /** Watch Region */
            watch_region: string | null;
            /**
             * Spoiler Free
             * @default true
             */
            spoiler_free: boolean;
            /**
             * Transparent
             * @default true
             */
            transparent: boolean;
        };
        /** ProviderView */
        ProviderView: {
            /** Id */
            id: string;
            /** Last Success */
            last_success: string | null;
            /** Error */
            error: string;
            /** Enabled */
            enabled: boolean;
        };
        /** ResolveCreator */
        ResolveCreator: {
            /** Url */
            url: string;
        };
        /** ReviewDecision */
        ReviewDecision: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "confirm" | "ignore";
            /**
             * Kind
             * @enum {string}
             */
            kind: "preview" | "recap";
            /** Expected Updated At */
            expected_updated_at: string;
        };
        /** ReviewList */
        ReviewList: {
            /** Items */
            items: components["schemas"]["ReviewView"][];
        };
        /** ReviewView */
        ReviewView: {
            /** Id */
            id: string;
            /** Video Id */
            video_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Creator */
            creator: string;
            /** Published At */
            published_at: string;
            /** Event Id */
            event_id: string;
            /** Event Title */
            event_title: string;
            /** Starts At */
            starts_at: string | null;
            /** Kind */
            kind: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Rule Version */
            rule_version: string;
            /** Updated At */
            updated_at: string;
        };
        /** SaveFollows */
        SaveFollows: {
            /** Expected Revision */
            expected_revision: number;
            /** Follows */
            follows: components["schemas"]["Follow"][];
        };
        /** SavePreferences */
        SavePreferences: {
            /** Expected Revision */
            expected_revision: number;
            preferences: components["schemas"]["Preferences-Input"];
        };
        /** ServiceStatusView */
        ServiceStatusView: {
            /** Local Preview */
            local_preview: boolean;
            /** Firebase Configured */
            firebase_configured: boolean;
            /** Providers */
            providers: components["schemas"]["ProviderView"][];
            /** Integrations */
            integrations: {
                [key: string]: string;
            };
        };
        /** SourceList */
        SourceList: {
            /** Items */
            items: components["schemas"]["SourceView"][];
        };
        /** SourceView */
        SourceView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /** Color */
            color: string;
            /** Sport */
            sport: string;
            /** Kind */
            kind: string;
            /** Demo */
            demo: boolean;
        };
        /** UpdateCreator */
        UpdateCreator: {
            /** Expected Revision */
            expected_revision: number;
            /** Scope Keys */
            scope_keys: string[];
            /** Preview */
            preview: boolean;
            /** Recap */
            recap: boolean;
            /** Enabled */
            enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatusView"];
                };
            };
        };
    };
    login_local_api_v1_auth_local_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarUserView"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sources_api_v1_sources_get: {
        parameters: {
            query?: {
                q?: string;
                dataset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                dataset?: string;
                followed?: boolean;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_detail_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_v1_me_calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarUserView"];
                };
            };
        };
    };
    follows_api_v1_me_follows_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveFollows"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarUserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preferences_api_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavePreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarUserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    selection_api_v1_events__event_id__selection_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_link_api_v1_events__event_id__links_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkAddedView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_api_v1_me_links__link_id__block_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    creator_resolve_api_v1_me_creators_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveCreator"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorIdentity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    creator_add_api_v1_me_creators_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCreator"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarUserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    creator_delete_api_v1_me_creators__channel_id__delete: {
        parameters: {
            query: {
                expected_revision: number;
                confirmed?: boolean;
            };
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarUserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    creator_update_api_v1_me_creators__channel_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCreator"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarUserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    creator_impact_api_v1_me_creators__channel_id__impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatorRemovalImpact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    creator_refresh_api_v1_me_creators__channel_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reviews_api_v1_me_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewList"];
                };
            };
        };
    };
    review_decide_api_v1_me_reviews__match_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_pin_api_v1_me_links__link_id__pin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_config_api_v1_me_config_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config-Output"];
                };
            };
        };
    };
    import_config_api_v1_me_config_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    address_api_v1_me_feed_address_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    rotate_api_v1_me_feed_rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_api_v1_me_feed_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feed_preview_api_v1_me_feed_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_sync_api_v1_local_providers__provider__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
